### ISSUE TITLE
a way to revert the hit direction fix

### ISSUE THREAD

**Issue by QueenUlyana** [RaderRMT/Timeless#1]
@RaderRMT  **Can I talk more about "a way to revert the hit direction fix"? An example video or something, I don't understand it.**

**Comment by RaderRMT** [comment]
[Here's a video](https://cdn.discordapp.com/attachments/904466942742655078/1096489592166809690/2023-04-14_19-37-27.mp4)

i added the video to the readme

**Comment by QueenUlyana** [comment]
> [Here's a video](https://cdn.discordapp.com/attachments/904466942742655078/1096489592166809690/2023-04-14_19-37-27.mp4)
> 
> i added the video to the readme

Thank you
