### ISSUE TITLE
Create new world background darkening

### ISSUE THREAD

**Issue by ruvaldak** [RaderRMT/Timeless#2]
The new world menu originally had the background darkened slightly like most other menus. Seems to be missing entirely here. Will upload screenshots momentarily.

**Comment by RaderRMT** [comment]
i can't really do anything about it, i use the same `renderBackground` method that mojang uses to render the dirt background on other screens.
even the new create new world menu is slightly brighter despite using the same `renderBackground` method

**Comment by ruvaldak** [comment]
can't just add a darkened overlay on top of the background to mimic the effect?

**Comment by RaderRMT** [comment]
Quick update, I'm currently porting the mod to 1.20.6 and I managed to get the darkened effect.

**Comment by RaderRMT** [comment]
fixed, will release along with all missing versions up to 1.21.4
