### ISSUE TITLE
Old World Menu changes the behavior of world creations with any seeds

### ISSUE THREAD

**Issue by Kichura** [RaderRMT/Timeless#3]
When creating a world for first time using any seed - The world generation suddenly changes to something else entirely,

What it looks like in vanilla:
![vanilla](https://github.com/RaderRMT/Timeless/assets/68134602/9f2393a9-af03-4c57-a88e-acc4d44813c8)

What it looks like with Timeless + Fabric API:
![timeless](https://github.com/RaderRMT/Timeless/assets/68134602/71c58179-8b3f-45a8-a628-e94b54e46df7)

Technical infos:

Seed = 1920
Version: Minecraft 1.20.1,
Timeless version: 1.20.1-1.1.0,
Fabric API: 0.83.1+1.20.1.

**Comment by RaderRMT** [comment]
fixed. you can update the mod
