### ISSUE TITLE
[Bug] OldWorldMenu

### ISSUE THREAD

**Issue by QueenUlyana** [RaderRMT/Timeless#4]
**It does not allow you to create a world with a chosen seed, it creates worlds with random seeds. How did you miss that?**
@RaderRMT

**Comment by RaderRMT** [comment]
> How did you miss that?

no particular reason. I'm a human, and humans forget stuff

i'll fix it asap

**Comment by RaderRMT** [comment]
also, duplicate of #3

**Comment by RaderRMT** [comment]
fixed. please update
